### ISSUE TITLE
Переданные через passArgument данные приходят дважды.

### ISSUE THREAD

**Issue by smwed** [alphicc/Brick#12]
Здравствуйте.
(Я новичок и не знаю как правильно писать такие сообщения, поэтому поправьте меня если нужно.)

Используется: Android + Jetpack Compose.

Имеем:
1. childRouter - вложенный в mainRouter.
2. в childRouter два компонента TestA и TestB (оба имеют собственные viewModel и screenContent)
3. в viewModelTestB делаем childRouter.passArgument(TestA.key, "test")
4. в TestA данные приходят **дважды**
Если сделать mainRouter.passArgument(TestA.key, "test"), то данные приходят как положено - один раз.

Исследование показало, что в функции
_override suspend fun <A> redirectArgument(
        from: ArgumentTranslator,
        componentKey: String,
        argument: A
    ) {
        if (parentRouter !== from) {
            parentRouter?.redirectArgument(this, componentKey, argument)
        }
        childRouters.value.forEach { it.second.redirectArgument(this, componentKey, argument) }
        emitArguments(componentKey, argument)
    }_

отправка (emitArguments(...)) вызывается и для mainRouter (родительского) и для childRouter.

--- в моем коде так:
Объявление mainRouter:
_val mainRouter = TreeRouter.new()_

Объявление childRouter:
_private val childRouter by lazy {
        mainRouter.branch(Screens.mainScreen.key).apply {
            addComponent(Screens.TestA, this)
        }
    }_

Переход на TestB в TestAViewModel
_childRouter.addComponent(Screens.TestB, childRouter)_

Отправка данных в TestBViewModel:
_childRouter.passArgument(Screens.TestA.key, argument)_

Прием в TestAViewModel:
viewModelScope.launch {
            channel.collect { data ->
               //skip
            }
        }

Пожалуйста, подскажите, что я делаю не правильно?
Можем связаться через e-mail?

**Comment by alphicc** [comment]
Добрый день.

Мне необходимо попробовать воспроизвести Вашу проблему, у себя. Пока есть подозрение на баг.
Собираюсь заняться этой проблемой в ближайшее время.

**Comment by smwed** [comment]
Добрый день.

Если я правильно понимаю, то решение может быть в том, что emitArgument должно происходить только по дочерним компонентам/роутерам верхнего родительского роутера.
Может быть вот так?

override suspend fun redirectArgument(
from: ArgumentTranslator,
componentKey: String,
argument: A
) {
     if (parentRouter !== from) {
           parentRouter?.redirectArgument(this, componentKey, argument)
     } **else** {
          childRouters.value.forEach { it.second.redirectArgument(this, componentKey, argument) }
          emitArguments(componentKey, argument)
    }
}

**Comment by smwed** [comment]
> ...Собираюсь заняться этой проблемой в ближайшее время.

Добрый день.
Есть ли какое-либо продвижение?

**Comment by alphicc** [comment]
Добрый вечер, был загружен по работе. 
Работа успешно завершена, сейчас на этапе тестирования.
К вечеру уже будет релиз

**Comment by alphicc** [comment]
Релиз сделал, проверьте устранена ли проблема. 
В ближайшее время библиотеку можно будет подтянуть из репозитория

**Comment by smwed** [comment]
> Релиз сделал, проверьте устранена ли проблема. В ближайшее время библиотеку можно будет подтянуть из репозитория

Да, проблема устранена - данные приходят только 1 раз. Баг можно закрывать.
Большое спасибо!
